=== Javastro/astrogrid-legacy/astrogrid/pal/xdocs/xdoc.dtd
<!ELEMENT table (#PCDATA | thead | tbody)*>
<!ATTLIST table summary CDATA #IMPLIED>
<!ELEMENT subsection (#PCDATA | p | table | source | dl | ul | ol | blockquote)*>
<!ATTLIST subsection name CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author email CDATA #IMPLIED>
<!ELEMENT properties (#PCDATA | title | author)*>
<!ELEMENT tr (#PCDATA | th | td)*>
<!ELEMENT th (#PCDATA)>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th style CDATA #IMPLIED>
<!ELEMENT td (#PCDATA | a | em | ul | ol | img | br | b | code | acronym | strong)*>
<!ATTLIST td style CDATA #IMPLIED>
<!ELEMENT section (#PCDATA | p | table | subsection | source | dl | ul | ol | blockquote)*>
<!ATTLIST section name CDATA #IMPLIED>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a target CDATA #IMPLIED>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT img (#PCDATA)>
<!ATTLIST img height CDATA #IMPLIED>
<!ATTLIST img width CDATA #IMPLIED>
<!ATTLIST img alt CDATA #IMPLIED>
<!ATTLIST img src CDATA #IMPLIED>
<!ELEMENT document (#PCDATA | properties | head |  body)*>
<!ELEMENT thead (#PCDATA | tr)*>
<!ELEMENT tbody (#PCDATA | tr)*>
<!ELEMENT code (#PCDATA)>
<!ELEMENT br (#PCDATA)>
<!ELEMENT p (#PCDATA | a | em | ul | ol | img | br | b | code | acronym | strong )*>
<!ATTLIST p ref CDATA #IMPLIED>
<!ELEMENT blockquote (#PCDATA | a | em | ul | ol | img | br | b | code | acronym | strong )*>
<!ELEMENT source (#PCDATA)>
<!ELEMENT b (#PCDATA)>
<!ELEMENT body (#PCDATA | section)*>
<!ATTLIST body onload CDATA #IMPLIED>
<!ELEMENT em (#PCDATA)>
<!ELEMENT ul (#PCDATA | li)*>
<!ELEMENT ol (#PCDATA | li)* >
<!ELEMENT head (#PCDATA | style | script)*>
<!ELEMENT li (#PCDATA | a | em | ul | ol | img | br | b | code | acronym | strong | p )*>
<!ELEMENT style (#PCDATA)>
<!ATTLIST style type CDATA #IMPLIED>
<!ELEMENT script (#PCDATA)>
<!ATTLIST script type CDATA #IMPLIED>
<!ATTLIST body class CDATA #IMPLIED>
<!ELEMENT acronym (#PCDATA)>
<!ATTLIST acronym title CDATA #IMPLIED>
<!ELEMENT span (#PCDATA)>
<!ATTLIST span id CDATA #IMPLIED>
<!ELEMENT strong (#PCDATA)>

<!ELEMENT dl (#PCDATA | dt | dd)*>
<!ELEMENT dd (#PCDATA | a | em | ul | ol | img | br | b | code | acronym | strong | p )*>
<!ELEMENT dt (#PCDATA | a)*>
<!ENTITY nbsp   "&#160;"> <!-- no-break space = non-breaking space,
                           U+00A0 ISOnum -->

=== Javastro/astrogrid-legacy/astrogrid/applications/commandline/xdocs/installation-options.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE document SYSTEM "file:/C:/CVS-head/astrogrid/sampleDocs/xdocs/xdoc.dtd">
<document>
	<properties>
		<author email="gtr@ast.cam.ac.uk">Guy Rixon</author>
		<title>Installation options</title>
	</properties>
	
	<body>
		<p>This document discusses alternatives to the the standard installation.</p>
		
		<section name="Alternative web containers">
			<p>
			The standard installation requires Jakarta-Tomcat, at v5.0.19 for a production-network service and v5.0.28
				of a development-network service. Other containers, and other versions, of Tomcat <em>might</em> work but may
				introduce subtle errors. No other containers and versions are supported; Tomcat v5.0.28 is only supported in
				the sense that it is being used for AstroGrid's internal development.
			</p>
			<p>
				The web-application will probably not work in containers other than Tomcat. If you try one and get it to
				work, then please let the AstroGrid project know. If you try a container and hit problems, then it is
				likely that the web-application would need to be changed to run in this container. This is not a bug:
				AstroGrid components are not designed to work with other containers.
			</p>
			<p>
				Tomcat versions in the 5.0.x series can probably run the web-application. Versions after 5.0.19 are most
				likely to work.
			</p>
			<p>
				Tomcat versions in the 5.5.x series cannot run the web-application when Tomcat runs with Java 1.5; this
				has been shown empirically. Tomcat 5.5.x reconfigured for Java 1.4.x might work.
			</p>
			<p>
				Tomcat versions in the 4.1.x series might work.
			</p>
			<p>
				Tomcat versions in the 3.x series cannot run the web-application. They support an older edition of
				the servlet standard; the web-application requires servlet v2.3.
			</p>
		</section>
	</body>
</document>

=== Javastro/astrogrid-legacy/astrogrid/pal/xdocsOLD/queries.xml
<?xml version="1.0" ?>
<!DOCTYPE document SYSTEM "xdoc.dtd" >
<document>
<properties>
  <title>Query Examples</title>
  <author email="dave@ast.cam.ac.uk">Dave Morris</author>
  <author email="mch@roe.ac.uk">Martin Hill</author>
</properties>
<body>
<section name="Introduction">
<p>
This page contains some examples on how to run some queries on a dataserver
   directly from the service's pages, rather than through an AstroGrid portal.  For help
   on the AstroGrid portal, see [todo - link].
</p>
   <p>
      Because each dataservice is different - not just the form of the data but what the data
      represents can be different - the examples here are based upon the SampleStars dataset
      that comes with each skycatserver webapp as the initial, default 'test' dataset.
      See also <a href="samplestars.html">The SampleStars dataset</a>
   </p>
</section>

<section name="ADQL/SQL and ADQL/XML">
   <p>
      The Astronomy Data Query Language comes in two forms: an SQL-like form for human beings,
      and an XML form for computers and some of the more enthusiastic developers.  The SQL
      form is easier to read and write for humans, but can be a bit ambiguous.
   </p>
   <p>ADQL/SQL queries look like this:
   </p>
   <p><code>SELECT * FROM SOURCES WHERE SOURCES.DEC &gt; 88 AND SOURCES.TYPE = 'STAR'</code></p>
</section>
      
<section name="Cone search">
    <p>There are also extra astronomical functions added to ADQL.  The CIRCLE has been implemented
      for the AstroGird datacenters for cone searches, of the form <code>CIRCLE('equinox', ra, dec, radius)</code>
      for example:
       </p>
   <p><code>SELECT * FROM SOURCES WHERE CIRCLE('J2000', 57, 24, 2) </code></p>
   <p>will select those objects in the area of the pleidies, where ra=57, dec=24 and the radius=2 degrees.</p>
</section>

</body>
</document>
