=== Javastro/astrogrid-legacy/astrogrid/registry/maven-project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name="project">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="extend" minOccurs="0"/>
        <xs:element ref="pomVersion"/>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="groupId" minOccurs="0"/>
        <xs:element ref="currentVersion"/>
        <xs:element ref="organization"/>
        <xs:element ref="inceptionYear"/>
        <xs:element ref="package" minOccurs="0"/>
        <xs:element ref="logo" minOccurs="0"/>
        <xs:element ref="gumpRepositoryId" minOccurs="0"/>
        <xs:element ref="description" minOccurs="0"/>
        <xs:element ref="shortDescription"/>
        <xs:element ref="url" minOccurs="0" />
        <xs:element ref="issueTrackingUrl" minOccurs="0"/>
        <xs:element ref="siteAddress" minOccurs="0"/>
        <xs:element ref="siteDirectory" minOccurs="0"/>
        <xs:element ref="distributionDirectory" minOccurs="0"/>
        <xs:element ref="repository" minOccurs="0"/>
        <xs:element ref="versions" minOccurs="0"/>
        <xs:element ref="branches" minOccurs="0"/>
        <xs:element ref="mailingLists" minOccurs="0"/>
        <xs:element ref="developers"/>
        <xs:element ref="contributors" minOccurs="0"/>
        <xs:element ref="licenses" minOccurs="0"/>
        <xs:element ref="dependencies" minOccurs="0"/>
        <xs:element ref="build"/>
        <xs:element ref="reports" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="extend" type='xs:string'/>
  <xs:element name="connection" type='xs:string'/>
  <xs:element name="developerConnection" type='xs:string'/>
  <xs:element name="currentVersion" type='xs:string'/>
  <xs:element name="description" type='xs:string'/>
  <xs:element name="distributionDirectory" type='xs:string'/>
  <xs:element name="name" type='xs:string'/>
  <xs:element name="groupId" type='xs:string'/>
  <xs:element name="artifactId" type='xs:string'/>
  <xs:element name="gumpRepositoryId" type='xs:string'/>
  <xs:element name="id" type='xs:string'/>
  <xs:element name="inceptionYear" type='xs:string'/>
  <xs:element name="issueTrackingUrl" type='xs:string'/>
  <xs:element name="logo" type='xs:string'/>
  <xs:element name="package" type='xs:string'/>
  <xs:element name="pomVersion" type='xs:string'/>
  <xs:element name="shortDescription" type='xs:string'/>
  <xs:element name="siteAddress" type='xs:string'/>
  <xs:element name="siteDirectory" type='xs:string'/>
  <xs:element name="url" type='xs:string'/>
  <xs:element name="distribution" type='xs:string'/>

  <xs:element name="repository">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connection"/>
        <xs:element ref="developerConnection" minOccurs="0"/>
        <xs:element ref="url" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="organization">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="url" minOccurs="0" />
        <xs:element ref="logo" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="versions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="tag" type='xs:string'/>
  
  <xs:element name="branches">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="branch" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="branch">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="mailingLists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mailingList" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="mailingList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="subscribe"/>
        <xs:element ref="unsubscribe"/>
        <xs:element ref="archive" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="subscribe" type='xs:string'/>
  <xs:element name="unsubscribe" type='xs:string'/>
  <xs:element name="archive" type='xs:string'/>
  
  <xs:element name="developers">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="developer" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="developer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="id"/>
        <xs:element ref="email"/>
        <xs:element name="organization" type='xs:string' minOccurs="0"/>
        <xs:element ref="roles" minOccurs="0" />
        <xs:element ref="url" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="roles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="role" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="role" type='xs:string'/>

  <xs:element name="contributors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contributor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="contributor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="email" minOccurs="0" />
        <xs:element name="organization" type='xs:string' minOccurs="0"/>
        <xs:element ref="roles" minOccurs="0" />
        <xs:element ref="url" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="email" type='xs:string'/>
  
  <xs:element name="licenses">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="license" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="license">
    <xs:complexType>
      <xs:sequence>
        <!-- name of the license, e.g. ASL 1.1 -->
        <xs:element ref="name" minOccurs="0"/>
        <!-- fetchable version of the license -->
        <xs:element ref="url" minOccurs="0" />
        <!-- manual, repository, ben? -->
        <xs:element ref="distribution" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
      
  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dependency">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id" minOccurs="0" />
        <xs:element ref="groupId" minOccurs="0" />
        <xs:element ref="artifactId" minOccurs="0" />
        <xs:element name="version" type="xs:string" />
        <xs:element ref="jar" minOccurs="0"/>
        <xs:element ref="type" minOccurs="0"/>
        <xs:element ref="url" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="type" type='xs:string'/>
  <xs:element name="jar" type='xs:string'/>
  
  <xs:element name="build">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nagEmailAddress" minOccurs="0"/>
        <xs:element ref="sourceDirectory" minOccurs="0"/>
        <xs:element ref="unitTestSourceDirectory" minOccurs="0"/>
        <xs:element ref="integrationUnitTestSourceDirectory" minOccurs="0"/>
        <xs:element ref="aspectSourceDirectory" minOccurs="0"/>
        <xs:element ref="unitTest" minOccurs="0"/>
        <xs:element ref="integrationUnitTest" minOccurs="0"/>
        <xs:element ref="resources" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nagEmailAddress" type='xs:string'/>

  <xs:element name="sourceDirectory" type='xs:string'/>
  <xs:element name="unitTestSourceDirectory" type='xs:string'/>
  <xs:element name="integrationUnitTestSourceDirectory" type='xs:string'/>
  <xs:element name="aspectSourceDirectory" type='xs:string'/>
  
  <xs:element name="unitTest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="includes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="excludes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="include" type='xs:string'/>
  <xs:element name="exclude" type='xs:string'/>
  
  <xs:element name="integrationUnitTest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resource" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="directory" type='xs:string'/>
  <xs:element name="targetPath" type='xs:string'/>

  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <!-- FIXME: I think that this defaults to basedir, need a check -->
        <xs:element ref="directory" minOccurs="0" />
        <xs:element ref="targetPath" minOccurs="0" />
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  

  <xs:element name="reports">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="report" minOccurs="0" maxOccurs="unbounded" 
          type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Javastro/astrogrid-legacy/astrogrid/registry/maven/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--+
    | Maven project description for the AstroGrid registry components.
    +-->
<project
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="maven-project.xsd">

    <!--+
        | The current version of the Maven project descriptor.
        +-->
    <pomVersion>3</pomVersion>

    <!--+
        | The short name of the project group.
        | This value is used to group all jars for a project in one directory.
        +-->
    <groupId>org.astrogrid</groupId>

    <!--+
        | The current version of the project.
        | This value is used when naming jars and distribution files.
        +-->
    <currentVersion>${astrogrid.iteration}</currentVersion>

    <!--+
        | The cvs repository location.
        +-->
    <repository>
        <connection>
            scm:cvs:pserver:anoncvs@cvs.astrogrid.org:/devel:astrogrid/registry
        </connection>
        <developerConnection>
            scm:cvs:ext:${maven.username}@cvs.astrogrid.org:/devel:astrogrid/registry
        </developerConnection>
    </repository>

    <!--+
        | Bugzilla URL.
        +-->
	<issueTrackingUrl>http://www.astrogrid.org/bugzilla/</issueTrackingUrl>

    <!--+
        | The project developers.
        +-->
	<developers>
	    <!--+
	        | Kevin Benson
	        +-->
		<developer>
			<name>Kevin Benson</name>
			<id>KevinBenson</id>
			<email>kmb@mssl.ucl.ac.uk</email>
			<organization>MSSL</organization>
			<roles>
				<role>Work group leader</role>
			</roles>
		</developer>
	    <!--+
	        | Brian McIlwrath
	        +-->
		<developer>
			<name>Brian McIlwrath</name>
			<id>bkm</id>
			<email>bkm@star.rl.ac.uk</email>
			<organization>CCLRC/RAL/SSTD/Astrogrid</organization>
			<roles>
				<role>Software developer</role>
			</roles>
		</developer>
	    <!--+
	        | Dave Morris
	        +-->
		<developer>
			<name>Dave Morris</name>
			<id>dave</id>
			<email>maven-report@codon.demon.co.uk</email>
			<organization>IoA Cambridge</organization>
			<roles>
				<role>Software developer</role>
			</roles>
		</developer>
	</developers>

    <!--+
        | Describes the licenses for this project.
    <licenses>
    </licenses>
        +-->

    <!--+
        | The external libraries required to build our components.
        +-->
    <dependencies>
        <!--+
            | The Axis webapp war file.
            +-->
        <dependency>
            <groupId>axis</groupId>
            <artifactId>axis</artifactId>
            <version>1.1</version>
            <type>war</type>
            <url>http://ws.apache.org/axis/index.html</url>
        </dependency>
        <!--+
            | The 3rd party jars that Axis depends on.

        <dependency>
            <groupId>jaf</groupId>
            <artifactId>jaf</artifactId>
            <version>1.0.2</version>
            <type>jar</type>
        </dependency>
            +-->        
        <!--+
            | The JConfig jars.
            | Soon to be replaced by the AstroGrid common tools.

        <dependency>
            <groupId>jconfig</groupId>
            <artifactId>jconfig</artifactId>
            <version>2.2</version>
            <type>jar</type>
            <url>http://www.jconfig.org/</url>
            <properties>
                <dist.zip>true</dist.zip>
            </properties>
        </dependency>
                    +-->
    </dependencies>

    <!--+
        | The list of reports to generate for each component.
        +-->
    <reports>
        <report>
            maven-changelog-plugin
        </report>
        <report>
            maven-changes-plugin
        </report>
        <report>
            maven-checkstyle-plugin
        </report>
        <report>
            maven-clover-plugin
        </report>
        <report>
            maven-developer-activity-plugin
        </report>
        <report>
            maven-file-activity-plugin
        </report>
        <report>
            maven-javadoc-plugin
        </report>
        <report>
            maven-junit-report-plugin
        </report>
        <report>
            maven-jxr-plugin
        </report>
        <report>
            maven-license-plugin
        </report>
        <report>
            maven-pmd-plugin
        </report>
        <report>
            maven-tasklist-plugin
        </report>
        <report>
            maven-simian-plugin
        </report>
    </reports>

</project>

=== Javastro/astrogrid-legacy/astrogrid/ogsa/ag-ogsa-echo/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<project
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="maven-project.xsd">

  <pomVersion>1</pomVersion>
  <id>astrogrid-ogsa-echo</id>
  <name>AstroGrid OGSA Echo</name>

  <currentVersion>HEAD</currentVersion>
  
  <organization>
    <name>AstroGrid</name>
    <url>http://www.astrogrid.org</url>
    <logo>http://www.astrogrid.org/images/AGlogo</logo>
  </organization>

  <inceptionYear>2002</inceptionYear>
  <package>org.astrogrid</package>
  <logo>http://www.astrogrid.org/images/AGlogo</logo>

  <shortDescription>AstroGrid OGSA Echo Gridservice</shortDescription>

	<!--
  <siteDirectory>/var/www/www/maven/build/datacenter</siteDirectory>
  -->

  <repository>
    <connection>
      scm:cvs:pserver:anoncvs@cvs.astrogrid.org:/devel:astrogrid/ogsa/echo
    </connection>
    <developerConnection>
      scm:cvs:ext:${maven.username}@cvs.astrogrid.org:/devel:astrogrid/ogsa/echo
    </developerConnection>
  </repository>

  <developers>
    <developer>
      <name>Guy Rixon</name>
      <id>gtr</id>
      <email>gtr@ast.cam.ac.uk</email>
    </developer>

  </developers>

  <dependencies>

    <dependency>
      <id>ogsa</id>
      <version>3.0</version>
    </dependency>

    <dependency>
      <id>saaj</id>
      <version>OGSA3.0</version>
    </dependency>

    <dependency>
      <id>cog-jglobus</id>
      <version>OGSA3.0</version>
    </dependency>

    <dependency>
      <id>xmlParserAPIs</id>
      <version>OGSA3.0</version>
    </dependency>

    <dependency>
      <id>jaxrpc</id>
      <version>OGSA3.0</version>
    </dependency>

    <dependency>
      <id>cog-axis</id>
      <version>OGSA3.0</version>
    </dependency>

    <dependency>
      <id>axis</id>
      <version>OGSA3.0</version>
    </dependency>

  </dependencies>

  <build>

    <sourceDirectory>build/src/java</sourceDirectory>
<!--
    <sourceDirectory>src/java</sourceDirectory>
    <unitTestSourceDirectory>test/java</unitTestSourceDirectory>

    <unitTest>
      <includes>
        <include>**/*Test.java</include>
      </includes>

      <resources>
        <resource>
          <directory>${basedir}/test/java</directory>
          <includes>
            <include>**/*.xml</include>
	    <include>**/*.properties</include>
          </includes>
        </resource>
      </resources>
    </unitTest>
	 -->

    <resources>
    	<resource><!-- config files -->
		<directory>${basedir}/src/java</directory>
		<includes>
			<include>**/*.xml</include>
			<include>**/*.properties</include>
		</includes>
	</resource>
	<resource> <!-- schemas  - may be needed for validation -->
		<directory>${basedir}</directory>
		<includes>
			<include>schema/*.xsd</include>
			<include>schema/*.dtd</include>
		</includes>
	</resource>
	<resource> <!-- webservice related files -->
		<directory>${basedir}</directory>
		<includes>
			<include>wsdl/*.wsdl</include>
			<include>wsdd/*.wsdd</include>
		</includes>
	</resource>
    </resources>

  </build>

  <reports>
    <report>
      maven-changelog-plugin
    </report>
    <report>
      maven-changes-plugin
    </report>
    <report>
      maven-checkstyle-plugin
    </report>
    <report>
      maven-clover-plugin
    </report>
    <report>
      maven-developer-activity-plugin
    </report>
    <report>
      maven-file-activity-plugin
    </report>
    <report>
      maven-javadoc-plugin
    </report>
    <report>
      maven-jdepend-plugin
    </report>
    <report>
      maven-junit-report-plugin
    </report>
    <report>
      maven-jxr-plugin
    </report>
    <report>
      maven-license-plugin
    </report>
    <report>
      maven-linkcheck-plugin
    </report>
    <report>
      maven-pmd-plugin
    </report>
    <report>
      maven-tasklist-plugin
    </report>
    <report>
      maven-simian-plugin
    </report>
  </reports>
</project>

=== Javastro/astrogrid-legacy/astrogrid/slinger/webnode/project.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- $Id: project.xml,v 1.2 2005/02/15 18:31:57 mch Exp $ -->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

    xsi:noNamespaceSchemaLocation="../../maven-base/xsd/maven-project.xsd">

    <!--will eventually extend from /base when Maven RC3 installed-->

    <extend>${basedir}/../../maven-base/project.xml</extend>

    <currentVersion>${astrogrid.slinger.version}</currentVersion>

    <id>astrogrid-slinger-webnode</id>

    <name>Astrogrid Slinger WebNode Package</name>

    <description>Webapp wrapper for Slinger</description>

    <shortDescription>AstroGrid Slinger Webapp</shortDescription>

    <dependencies>

        <dependency>
            <artifactId>astrogrid-common</artifactId>
            <groupId>org.astrogrid</groupId>
            <version>${astrogrid.common.version}</version>
        </dependency>

        <dependency>
            <artifactId>astrogrid-slinger-api</artifactId>
            <groupId>org.astrogrid</groupId>
            <version>${astrogrid.slinger.version}</version>
        </dependency>

        <dependency>
            <artifactId>astrogrid-slinger-xml</artifactId>
            <groupId>org.astrogrid</groupId>
            <version>${astrogrid.slinger.version}</version>
        </dependency>


         <!-- for logging -->
        <dependency>
            <artifactId>log4j</artifactId>
            <groupId>log4j</groupId>
            <version>1.2.4</version>
        </dependency>

        <dependency>
            <artifactId>commons-logging</artifactId>
            <groupId>commons-logging</groupId>
            <version>1.0.3</version>
        </dependency>

       <!-- servlet support -->
       <dependency>
         <id>servletapi</id>
         <version>2.3</version>
       </dependency>


    </dependencies>

</project>

=== Javastro/astrogrid-legacy/astrogrid/portal/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<project
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="maven-project.xsd">
  <pomVersion>3</pomVersion>
  
  <id>astrogrid-portal-wrapper</id>
  <name>AstroGrid Portal Wrapper</name>
  <groupId>astrogrid-portal</groupId>

  <currentVersion>HEAD</currentVersion>
  
  <organization>
    <name>AstroGrid</name>
    <url>http://www.astrogrid.org</url>
  </organization>
  
  <inceptionYear>2002</inceptionYear>
  
  <package>org.astrogrid.portal</package>
  
  <description>
    The AstroGrid Web Portal: access to AstroGrid via Cocoon.
  </description>
  <shortDescription>AstroGrid Web Portal</shortDescription>
  
  <url>http://www.astrogrid.org</url>
  
  <repository>
    <connection>
      scm:cvs:pserver:anoncvs@cvs.astrogrid.org:/devel/astrogrid:portal
    </connection>
    <developerConnection>
      scm:cvs:ext:${maven.user}@cvs.astrogrid.org:/devel/astrogrid:portal
    </developerConnection>
  </repository>
  
  <developers>
    <developer>
      <name>Peter Shillan</name>
      <id>gps</id>
      <email>gps@roe.ac.uk</email>
    </developer>

    <developer>
      <name>Pedro Contreras</name>
      <id>pcontrer</id>
      <email>p.contreras@qub.ac.uk</email>
    </developer>

    <developer>
      <name>Phillip Nicolson</name>
      <id>pjn3</id>
      <email>pjn3@star.le.ac.uk</email>
    </developer>

    <developer>
      <name>Roy Platon</name>
      <id>rtp</id>
      <email>R.T.Platon@rl.ac.uk</email>
    </developer>
  </developers>
  
  <dependencies>
    <!-- Common -->
    <dependency>
      <groupId>astrogrid-common</groupId>
      <artifactId>astrogrid-common</artifactId>
      <version>SNAPSHOT</version>
    </dependency>

    <!--
      Testing Utilities.
      -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
    </dependency>

    <dependency>
      <groupId>log4j</groupId>
      <artifactId>log4j</artifactId>
      <version>1.2.8</version>
    </dependency>
  </dependencies>
  
  <build>
    <sourceDirectory/>
    <unitTestSourceDirectory/>
  </build>
</project>

=== Javastro/astrogrid-legacy/astrogrid/filestore/maven/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--+
    |
    | <cvs:source>$Source: /Users/pharriso/Work/ag/repo/git/astrogrid-mirror/astrogrid/filestore/maven/project.xml,v $</cvs:source>
    | <cvs:author>$Author: jdt $</cvs:author>
    | <cvs:date>$Date: 2004/12/13 14:49:21 $</cvs:date>
    | <cvs:version>$Revision: 1.9 $</cvs:version>
    | <cvs:log>
    |   $Log: project.xml,v $
    |   Revision 1.9  2004/12/13 14:49:21  jdt
    |   Some pruning, that factors out more of the commonality into maven-base
    |
    |   Revision 1.8  2004/11/25 00:19:20  jdt
    |   Merge from dave-dev-200410061224-200411221626
    |
    |   Revision 1.7  2004/11/23 18:40:50  jdt
    |   Merges from  BLD_JDT_648.  The long awaited move to versioned jars and wars.  Fingers crossed.  See:
    |   http://software.astrogrid.org/developerdocs/developmentprocess.html
    |
    |   Revision 1.6.24.1  2004/11/12 00:45:52  jdt
    |   Switched to use fixed version numbers, defined in a properties file
    |
    |   Revision 1.6  2004/09/17 06:57:10  dave
    |   Added commons logging to FileStore.
    |   Updated logging properties in Community.
    |   Fixed bug in AGINAB deployment.
    |   Removed MySpace tests with hard coded grendel address.
    |
    |   Revision 1.5.32.1  2004/09/17 01:08:36  dave
    |   Updated debug to use commons logging API ....
    |
    |   Revision 1.5  2004/08/18 19:00:01  dave
    |   Myspace manager modified to use remote filestore.
    |   Tested before checkin - integration tests at 91%.
    |
    |   Revision 1.4.2.1  2004/07/27 15:50:54  dave
    |   Changed tabs to spaces
    |
    |   Revision 1.4  2004/07/27 12:16:07  jdt
    |   whoopsie
    |
    |   Revision 1.3  2004/07/27 11:46:27  jdt
    |   Projects MUST extend maven-base and not override <currentVersion>
    |
    |   Revision 1.2  2004/07/14 13:50:29  dave
    |   Merged development branch, dave-dev-200406301228, into HEAD
    |
    |   Revision 1.1.2.1  2004/07/05 04:50:29  dave
    |   Created initial FileStore components
    |
    | </cvs:log>
    |
    +-->
<project
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ant="jelly:ant"
    xsi:noNamespaceSchemaLocation="maven-project.xsd">
    <!--+
        | Extend the global astrogrid project.xml.
        +-->
    <extend>../../maven-base/project.xml</extend>
    <currentVersion>${astrogrid.filestore.version}</currentVersion>

    <!--+
        | The Java package name of the project.
        +-->
    <package>org.astrogrid.filestore</package>

    <!--+
        | The external libraries required to build our components.
        +-->
    <dependencies>
        <!--+
            | The Axis webapp war file.
            +-->
        <dependency>
            <groupId>axis</groupId>
            <artifactId>axis</artifactId>
            <version>1.1</version>
            <type>war</type>
            <url>http://ws.apache.org/axis/index.html</url>
        </dependency>
        <!--+
            | JUnit library for test tasks.
            +-->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <type>jar</type>
            <url>http://www.junit.org/</url>
        </dependency>
        <!--+
            | Ant library for test tasks.
            +-->
        <dependency>
            <groupId>ant</groupId>
            <artifactId>ant</artifactId>
            <version>1.5.3-1</version>
            <type>jar</type>
            <url>http://ant.apache.org/</url>
        </dependency>
        <!--+
            | Commons logging API.
            +-->
        <dependency>
            <artifactId>commons-logging</artifactId>
            <groupId>commons-logging</groupId>
            <version>1.0.3</version>
            <properties>
                <war.bundle>true</war.bundle>
            </properties>
        </dependency>
        <!--+
            | Log4j toolkit.
            +-->
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.8</version>
            <properties>
                <war.bundle>true</war.bundle>
            </properties>
        </dependency>
    </dependencies>
</project>
