=== Javastro/astrogrid-legacy/astrogrid/registry/maven-project.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
  <xs:element name="project">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="extend" minOccurs="0"/>
        <xs:element ref="pomVersion"/>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="groupId" minOccurs="0"/>
        <xs:element ref="currentVersion"/>
        <xs:element ref="organization"/>
        <xs:element ref="inceptionYear"/>
        <xs:element ref="package" minOccurs="0"/>
        <xs:element ref="logo" minOccurs="0"/>
        <xs:element ref="gumpRepositoryId" minOccurs="0"/>
        <xs:element ref="description" minOccurs="0"/>
        <xs:element ref="shortDescription"/>
        <xs:element ref="url" minOccurs="0" />
        <xs:element ref="issueTrackingUrl" minOccurs="0"/>
        <xs:element ref="siteAddress" minOccurs="0"/>
        <xs:element ref="siteDirectory" minOccurs="0"/>
        <xs:element ref="distributionDirectory" minOccurs="0"/>
        <xs:element ref="repository" minOccurs="0"/>
        <xs:element ref="versions" minOccurs="0"/>
        <xs:element ref="branches" minOccurs="0"/>
        <xs:element ref="mailingLists" minOccurs="0"/>
        <xs:element ref="developers"/>
        <xs:element ref="contributors" minOccurs="0"/>
        <xs:element ref="licenses" minOccurs="0"/>
        <xs:element ref="dependencies" minOccurs="0"/>
        <xs:element ref="build"/>
        <xs:element ref="reports" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="extend" type='xs:string'/>
  <xs:element name="connection" type='xs:string'/>
  <xs:element name="developerConnection" type='xs:string'/>
  <xs:element name="currentVersion" type='xs:string'/>
  <xs:element name="description" type='xs:string'/>
  <xs:element name="distributionDirectory" type='xs:string'/>
  <xs:element name="name" type='xs:string'/>
  <xs:element name="groupId" type='xs:string'/>
  <xs:element name="artifactId" type='xs:string'/>
  <xs:element name="gumpRepositoryId" type='xs:string'/>
  <xs:element name="id" type='xs:string'/>
  <xs:element name="inceptionYear" type='xs:string'/>
  <xs:element name="issueTrackingUrl" type='xs:string'/>
  <xs:element name="logo" type='xs:string'/>
  <xs:element name="package" type='xs:string'/>
  <xs:element name="pomVersion" type='xs:string'/>
  <xs:element name="shortDescription" type='xs:string'/>
  <xs:element name="siteAddress" type='xs:string'/>
  <xs:element name="siteDirectory" type='xs:string'/>
  <xs:element name="url" type='xs:string'/>
  <xs:element name="distribution" type='xs:string'/>

  <xs:element name="repository">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="connection"/>
        <xs:element ref="developerConnection" minOccurs="0"/>
        <xs:element ref="url" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="organization">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="url" minOccurs="0" />
        <xs:element ref="logo" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="versions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id"/>
        <xs:element ref="name"/>
        <xs:element ref="tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="tag" type='xs:string'/>
  
  <xs:element name="branches">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="branch" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="branch">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tag"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="mailingLists">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="mailingList" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="mailingList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="subscribe"/>
        <xs:element ref="unsubscribe"/>
        <xs:element ref="archive" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="subscribe" type='xs:string'/>
  <xs:element name="unsubscribe" type='xs:string'/>
  <xs:element name="archive" type='xs:string'/>
  
  <xs:element name="developers">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="developer" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="developer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="id"/>
        <xs:element ref="email"/>
        <xs:element name="organization" type='xs:string' minOccurs="0"/>
        <xs:element ref="roles" minOccurs="0" />
        <xs:element ref="url" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="roles">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="role" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="role" type='xs:string'/>

  <xs:element name="contributors">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="contributor" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="contributor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="email" minOccurs="0" />
        <xs:element name="organization" type='xs:string' minOccurs="0"/>
        <xs:element ref="roles" minOccurs="0" />
        <xs:element ref="url" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="email" type='xs:string'/>
  
  <xs:element name="licenses">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="license" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="license">
    <xs:complexType>
      <xs:sequence>
        <!-- name of the license, e.g. ASL 1.1 -->
        <xs:element ref="name" minOccurs="0"/>
        <!-- fetchable version of the license -->
        <xs:element ref="url" minOccurs="0" />
        <!-- manual, repository, ben? -->
        <xs:element ref="distribution" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
      
  <xs:element name="dependencies">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dependency" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="dependency">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="id" minOccurs="0" />
        <xs:element ref="groupId" minOccurs="0" />
        <xs:element ref="artifactId" minOccurs="0" />
        <xs:element name="version" type="xs:string" />
        <xs:element ref="jar" minOccurs="0"/>
        <xs:element ref="type" minOccurs="0"/>
        <xs:element ref="url" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="type" type='xs:string'/>
  <xs:element name="jar" type='xs:string'/>
  
  <xs:element name="build">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nagEmailAddress" minOccurs="0"/>
        <xs:element ref="sourceDirectory" minOccurs="0"/>
        <xs:element ref="unitTestSourceDirectory" minOccurs="0"/>
        <xs:element ref="integrationUnitTestSourceDirectory" minOccurs="0"/>
        <xs:element ref="aspectSourceDirectory" minOccurs="0"/>
        <xs:element ref="unitTest" minOccurs="0"/>
        <xs:element ref="integrationUnitTest" minOccurs="0"/>
        <xs:element ref="resources" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="nagEmailAddress" type='xs:string'/>

  <xs:element name="sourceDirectory" type='xs:string'/>
  <xs:element name="unitTestSourceDirectory" type='xs:string'/>
  <xs:element name="integrationUnitTestSourceDirectory" type='xs:string'/>
  <xs:element name="aspectSourceDirectory" type='xs:string'/>
  
  <xs:element name="unitTest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="includes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="excludes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="include" type='xs:string'/>
  <xs:element name="exclude" type='xs:string'/>
  
  <xs:element name="integrationUnitTest">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="resources">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="resource" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="directory" type='xs:string'/>
  <xs:element name="targetPath" type='xs:string'/>

  <xs:element name="resource">
    <xs:complexType>
      <xs:sequence>
        <!-- FIXME: I think that this defaults to basedir, need a check -->
        <xs:element ref="directory" minOccurs="0" />
        <xs:element ref="targetPath" minOccurs="0" />
        <xs:element ref="includes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="excludes" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  

  <xs:element name="reports">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="report" minOccurs="0" maxOccurs="unbounded" 
          type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Javastro/astrogrid-legacy/astrogrid/security/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<project
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="maven-project.xsd">

  <extend>../maven-base/project.xml</extend>
  
  <artifactId>astrogrid-security</artifactId>
  <currentVersion>${astrogrid.security.version}</currentVersion>
  <name>AstroGrid security facade</name>

  <shortDescription>A collection of APIs abstracting security in web services.</shortDescription>
  
  <description>
    <![CDATA[
    <p>
    The security-facade package implements a single-sign-on (SSO) authentication 
    system between SOAP clients and SOAP services. Messages sent with the aid of 
    this package are annotated with SSO credentials in the SOAP headers. Messages
    received by services using this package are authenticated using the credentials
    in the message.
    </p>
  	<p>
  	The current implementation is based on Axis and WSS4J. It enforces digital
  	signatures on requests from clients to services in line with the emerging
  	IVOA standard for SSO.
  	</p>
    <p>
    The facade hides details of the authentication from the client and service code.
  	Services alter their WSDD configuration to use the facade. Clients call the
  	facade's APIs, with the Axis-specific security calls encapsulated in the axis-specific
  	delegates.
  	</p>
  	<p>
  	At present, this implementation reads in credentials from files local to the
  	clients. It does not use the AstroGrid community-services and does not
  	depend on other AstroGrid components.
  	</p>
    ]]>
  </description>
  
  <dependencies>
     
    <dependency>
      <groupId>axis</groupId>
      <type>jar</type>
      <artifactId>axis</artifactId>
      <version>1.2.1</version>
    </dependency>

    <dependency>
      <groupId>saaj</groupId>
      <type>jar</type>
      <artifactId>saaj</artifactId>
      <version>unknown</version>
      <jar>saaj.jar</jar>
    </dependency>

    <dependency>
      <groupId>commons-logging</groupId>
      <type>jar</type>
      <artifactId>commons-logging</artifactId>
      <version>1.0.3</version>
    </dependency>

    <dependency>
      <groupId>commons-discovery</groupId>
      <type>jar</type>
      <artifactId>commons-discovery</artifactId>
      <version>20030211.213356</version>
    </dependency>
    
    <dependency>
      <groupId>castor</groupId>
      <type>jar</type>
      <artifactId>castor-xml</artifactId>
      <version>0.9.5</version>
      <jar>castor-0.9.5-xml.jar</jar>
    </dependency>
    
    <dependency>
      <groupId>jaxrpc-api</groupId>
      <type>jar</type>
      <artifactId>jaxrpc-api</artifactId>
      <version>1.0.3</version>
    </dependency>
    
    <dependency>
      <groupId>xml-apis</groupId>
      <type>jar</type>
      <artifactId>xml-apis</artifactId>
      <version>2.0.2</version>
    </dependency>
    
    <dependency>
      <groupId>wsdl4j</groupId>
      <type>jar</type>
      <artifactId>wsdl4j</artifactId>
      <version>1.0</version>
    </dependency>

    <dependency>
      <groupId>log4j</groupId>
      <type>jar</type>
      <artifactId>log4j</artifactId>
      <version>1.2.8</version>
    </dependency>
      
    <!-- DOM4J is used in the test classes. -->
    <dependency>
      <groupId>dom4j</groupId>
      <type>jar</type>
      <artifactId>dom4j</artifactId>
      <version>1.4</version>
    </dependency>
  	
  	<dependency>
  		<groupId>wss4j</groupId>
  		<type>jar</type>
  		<artifactId>wss4j</artifactId>
  		<version>1.0a</version>
  	</dependency>
  	
  	<dependency>
  		<groupId>xmlsec</groupId>
  		<type>jar</type>
  		<artifactId>xmlsec</artifactId>
  		<version>1.2.1</version>
  	</dependency>
    
  	<dependency>
  		<groupId>opensaml</groupId>
  		<type>jar</type>
  		<artifactId>opensaml</artifactId>
  		<version>1.1b</version>
  	</dependency>
  	
  	<dependency>
  		<groupId>bouncycastle</groupId>
  		<type>jar</type>
  		<artifactId>bcprov-jdk14</artifactId>
  		<version>129</version>
  	</dependency>
  	
  	<dependency>
  		<groupId>xalan</groupId>
  		<type>jar</type>
  		<artifactId>xalan</artifactId>
  		<version>2.6.0</version>
  	</dependency>
  	
  	<dependency>
  		<groupId>sun</groupId>
  		<type>jar</type>
  		<artifactId>mail</artifactId>
  		<version>1.3.1</version>
  	</dependency>
  	
  	<dependency>
  		<groupId>activation</groupId>
  		<type>jar</type>
  		<artifactId>activation</artifactId>
  		<version>1.0.2</version>
  	</dependency>
  	
  </dependencies>
	

  <build>
    <sourceDirectory>src/java</sourceDirectory>
    <unitTestSourceDirectory>test/java</unitTestSourceDirectory>

    <unitTest>
      <includes>
        <include>**/*Test.java</include>
      </includes>

      <resources>
        <resource>
          <directory>${basedir}/test/properties</directory>
          <includes>
 	    			<include>*.properties</include>
          </includes>
        </resource>
      </resources>
    </unitTest>

  </build>


</project>

=== Javastro/astrogrid-legacy/astrogrid/pal/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Id: project.xml,v 1.1.1.1 2005/02/17 18:37:34 mch Exp $ -->
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../maven-base/xsd/maven-project.xsd">
    <extend>../maven-base/project.xml</extend>
    <id>astrogrid-pal</id>
    <name>Publishers' Astrogrid Library</name>
    <description> A set of libraries and webapps for data publishers
    </description>
    <shortDescription>Publishers' Astrogrid Library</shortDescription>
    <build>
        <sourceDirectory/>
        <unitTestSourceDirectory/>
    </build>
</project>

=== Javastro/astrogrid-legacy/astrogrid/filestore/stress/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--+
    |
    | <cvs:source>$Source: /Users/pharriso/Work/ag/repo/git/astrogrid-mirror/astrogrid/filestore/stress/project.xml,v $</cvs:source>
    | <cvs:author>$Author: clq2 $</cvs:author>
    | <cvs:date>$Date: 2005/09/06 12:45:22 $</cvs:date>
    | <cvs:version>$Revision: 1.2 $</cvs:version>
    | <cvs:log>
    |   $Log: project.xml,v $
    |   Revision 1.2  2005/09/06 12:45:22  clq2
    |   dave-dev-200507251101
    |
    |   Revision 1.1.2.1  2005/08/04 12:29:52  dave
    |   Added large data (1Gbyte) stress test.
    |   Added JDK 1.5 fix to FileStoreOutputStream.
    |
    | </cvs:log>
    |
    +-->
<project
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="maven-project.xsd">

    <!--+
        | Extend the common project descriptor.
        +-->
    <extend>../maven/project.xml</extend>

    <!--+
        | The short name of the project.
        +-->
    <id>astrogrid-filestore-stress</id>

    <!--+
        | The full name of the project.
        +-->
    <name>FileStore stress tests</name>

    <!--+
        | A short description of the project.
        | The short description should be limited to a single line.
        +-->
    <shortDescription>
        FileStore stress tests, designed to be run against a live service installed in tomcat.
    </shortDescription>

    <!--+
        | A detailed description of the project.
        | This is used to generate the front page of the projects web site. 
        +-->
    <description>
        <![CDATA[
            FileStore stress tests, designed to be run against a live service installed in tomcat.
        ]]>
    </description>


    <!--+
        | The external libraries required to build our component.
        +-->
    <dependencies>
        <!--+
            | The AstroGrid common components.
            +-->
        <dependency>
            <groupId>${pom.groupId}</groupId>
            <artifactId>astrogrid-common</artifactId>
            <version>${astrogrid.common.version}</version>
            <type>jar</type>
            <url>http://www.astrogrid.org/</url>
        </dependency>
        <!--+
            | The FileStore components.
            +-->
        <dependency>
            <groupId>${pom.groupId}</groupId>
            <artifactId>astrogrid-filestore-common</artifactId>
            <version>${astrogrid.filestore.version}</version>
            <type>jar</type>
            <url>http://www.astrogrid.org/</url>
        </dependency>
        <dependency>
            <groupId>${pom.groupId}</groupId>
            <artifactId>astrogrid-filestore-client</artifactId>
            <version>${astrogrid.filestore.version}</version>
            <type>jar</type>
            <url>http://www.astrogrid.org/</url>
        </dependency>
        <!--+
            | The Registry components.
            +-->
        <dependency>
            <groupId>${pom.groupId}</groupId>
            <artifactId>astrogrid-registry-common</artifactId>
            <version>${astrogrid.registry.version}</version>
            <type>jar</type>
            <url>http://www.astrogrid.org/</url>
            <properties>
                <jar.fileset>true</jar.fileset>
            </properties>
        </dependency>
        <dependency>
            <groupId>${pom.groupId}</groupId>
            <artifactId>astrogrid-registry-client-lite</artifactId>
            <version>${astrogrid.registry.version}</version>
            <type>jar</type>
            <url>http://www.astrogrid.org/</url>
            <properties>
                <jar.fileset>true</jar.fileset>
            </properties>
        </dependency>
        <!--+
            | The commons HttpClient library.
            +-->
        <dependency>
            <id>commons-httpclient</id>
            <version>3.0-rc3</version>
            <url>http://jakarta.apache.org/commons/httpclient/3.0/</url>
            <type>jar</type>
            <properties>
                <jar.fileset>true</jar.fileset>
            </properties>
        </dependency>

    </dependencies>

    <!--+
        | The build properties for our project.
        +-->
    <build>
        <!--+
            | The location of our Java source code.
            +-->
        <sourceDirectory>src/java</sourceDirectory>
        <!--+
            | The location of our JUnit source code.
            +-->
        <unitTestSourceDirectory>src/junit</unitTestSourceDirectory>
        <!--+
            | Our JUnit test classes.
            +-->
        <unitTest>
            <!--+
                | Which tests to include.
                +-->
            <includes>
                <include>**/*TestCase.java</include>
            </includes>
            <!--+
                | The resources for our tests.
            <resources>
                <resource>
                </resource>
            </resources>
                +-->
        </unitTest>
    </build>

</project>
